version: '3.5'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: host.docker.internal  # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                     # Disable Running tests so the cluster starts faster
      DISABLE: hive,pulsar,azure-documentdb,blockchain,bloomberg,cassandra,coap,druid,elastic,elastic5,ftp,hazelcast,hbase,influxdb,jms,kudu,mongodb,mqtt,redis,rethink,voltdb,yahoo,hdfs,jdbc,elasticsearch,s3,twitter
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - C:/Users/Leo/git/kafka-connect-tile38-sink/target/kafka-connect-tile38-sink-1.0-SNAPSHOT-package/share/java/kafka-connect-tile38-sink:/connectors/Tile38
    links:
      - tile38

  tile38:
    image: tile38/tile38
    ports:
      - "9851:9851"

  source:
    image: leonardobonacci/train-source:1.0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      