version: '3.5'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: host.docker.internal  # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                     # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - C:/Users/Leo/git/kafka-connect-tile38-sink/target/kafka-connect-tile38-sink-1.0-SNAPSHOT-package/share/java/kafka-connect-tile38-sink:/connectors 
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - "xpack.security.enabled=false" 
    ports:
      - 9200:9200
      - 9300:9300

  source:
    image: leonardobonacci/train-source:1.0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      